name: CheckStyle,SpotBugs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle_spotbugs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

    - name: Generate gradle wrapper
      run: gradle wrapper --gradle-version=7.6

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build -x checkFormatMain

    - name: Run Checkstyle
      run: ./gradlew checkstyleMain

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: build/reports/checkstyle/main.html

    - name: Run SpotBugs
      run: ./gradlew spotbugsMain

    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs-report
        path: build/reports/spotbugs/
